#!/bin/bash 
echo "The school is open" 
#!/bin/bash 
"The School is open!"
#!/bin/bash 
["The school is open]
#!/bin/bash 
["The school is open!]
#!/bin/bash 
["The school is open!"]
"The school is open!"
